event:
    resource: "@EventBundle/Resources/config/routing.yml"
    prefix:   /

user_routes:
    resource: "@UserBundle/Controller"
    type: annotation

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
